# name: pytorch-devcontainer
services:
  pytorch-cpu:
    image: pytorch:2.2.0
    build:
      context: ../
      dockerfile: pytorch.Dockerfile
      args:
        VARIANT: 2.2.0-cuda12.1-cudnn8-runtime
        USERNAME: ${USER}
    container_name: pytorch-cpu
    hostname: pytorch-container
    user: ${USER}
    tty: true
    stdin_open: true
    shm_size: 16G
    working_dir: /mnt/
    volumes:
      - ${HOME}/Pytorch-Segmentation:/mnt/Pytorch-Segmentation
