# name: pytorch-devcontainer
services:
  pytorch:
    image: pytorch:2.0.0
    build:
      context: ../
      dockerfile: pytorch-2.0.0.Dockerfile
      args:
        USERNAME: ${USER}
    container_name: pytorch
    hostname: pytorch-container
    user: ${USER}
    tty: true
    stdin_open: true
    shm_size: 16G
    working_dir: /mnt/
    volumes:
      - ${HOME}/Pytorch-Segmentation:/mnt/Pytorch-Segmentation
