services:
  pytorch:
    image: pytorch:2.0.0
    build:
      context: .
      dockerfile: pytorch-2.0.0.Dockerfile
      args:
        USERNAME: kstef
        USER_ID: 1003
        GROUP_ID: 1003
      tags:
        - "pytorch:2.0.0"
    container_name: pytorch
    hostname: pytorch-container
    user: kstef
    tty: true
    stdin_open: true
    working_dir: /mnt/
    volumes:
      - /home/kstef/Pytorch-Segmentation:/mnt/Pytorch-Segmentation
      # - /home/kstef/.keras:/mnt/.keras
      - /home/kstef/dataset:/mnt/dataset
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['1']
              capabilities: [gpu]