# name: pytorch-devcontainer
services:
  pytorch:
    image: pytorch:2.0.0
    build:
      context: ../
      dockerfile: pytorch-2.0.0.Dockerfile
      args:
        USERNAME: ${USER}
    container_name: pytorch
    hostname: pytorch-container
    user: ${USER}
    tty: true
    stdin_open: true
    shm_size: 64G
    working_dir: /mnt/
    volumes:
      - ${HOME}/Pytorch-Segmentation:/mnt/Pytorch-Segmentation
      - ${DATAPATH}:/mnt/datasets:ro
      - ${HOME}/logs/Pytorch-Segmentation:/mnt/logs
    healthcheck:
      test: /usr/bin/nvidia-smi || exit 1
      interval: 5m
      timeout: 5s
      retries: 2
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 5
        window: 1m30s
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['0', '1']
              capabilities: [gpu]
