name: pytorch-devcontainer
services:
  pytorch:
    image: pytorch:2.0.0
    build:
      context: .
      dockerfile: pytorch-2.0.0.Dockerfile
      args:
        USERNAME: ${USER}
        USER_ID: ${UID}
        GROUP_ID: ${GID}
      tags:
        - "pytorch:2.0.0"
    container_name: pytorch-${USER}
    hostname: pytorch-container
    user: ${USER}
    tty: true
    stdin_open: true
    shm_size: 32G
    working_dir: /mnt/
    volumes:
      - ${HOME}/Pytorch-Segmentation:/mnt/Pytorch-Segmentation
      - /data/datasets/:/mnt/datasets:ro
      - ${HOME}/logs/Pytorch-Segmentation:/mnt/logs
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['0']
              capabilities: [gpu]
