model_config:
  name: deeplabv3-mobilenet_v3_large-1
  architecture: deeplabv3
  backbone: mobilenet_v3_large
  num_classes: 20
  unfreeze_at: block6a_expand_activation
  output_stride: 16
  activation: leaky_relu
  dropout_rate: 0

dataset_config:
  name: Cityscapes
  path: /mnt/dataset/Cityscapes/
  version: fine
  num_train_batches: 1.0 # 1.0 means 100% 
  num_eval_batches: 1.0
  batch_size: 6
  shuffle: yes
  num_workers: 4

train_config:
  loss: CrossEntropyLoss
  epochs: 30
  optimizer:
    name: Adam
    weight_decay: 0.00005
    momentum: 0.9
    learning_rate: 1e-3
  lr_schedule:
    name: Polynomial
    decay_epochs: 10
    power: 2
  distribute:
    strategy: auto
    sync_batchnorm: no
    devices: 2
  precision: high
  augmentations: 
    color_jitter: 
      contrast: 0.3
      brightness: 0.3
      saturation: 0.2
    horizontal_flip:
    gaussian_blur:
      sigma: [0.1, 3.0]

eval_config:
  eval_scales: [0.5, 1, 2]
  horrizontal_flip: no
  output_stride: 16 # NOT IMPEMENTED

inference_config:
  precision: high
  output_stride: 16 # NOT IMPEMENTED

logs_dir: /mnt/logs
