model_config:
  name: deeplabv3-mobilenet_v3_large-1
  architecture: deeplabv3 # Unet
  backbone: mobilenet_v3_large
  num_classes: 20
  unfreeze_at: block6a_expand_activation # block4a_expand_activation
  output_stride: 16
  filters: [16,32,64,128,256]
  activation: leaky_relu # swish, leaky_relu
  dropout_rate: 0
  pretrained_weights: #/root/Semantic-Segmentation-Cityscapes/pretrained_models/Mapillary/trunk

dataset_config:
  name: Cityscapes
  path: /mnt/dataset/Cityscapes/
  version: fine
  batch_size: 6
  num_train_batches: 1.0 # 1.0 means 100% 
  num_eval_batches: 1.0
  seed: 80
  num_workers: 6

train_config:
  loss: CrossEntropyLoss
  epochs: 10
  optimizer:
    name: Adam
    weight_decay: 0.00005
    momentum: 0.9
    learning_rate: 1e-3
  lr_schedule:
    name: Polynomial
    decay_epochs: 10
    power: 2
  distribute:
    strategy: ddp # NOT IMPEMENTED
    devices: 1
  precision: high
  augmentations: 
    color_jitter: 
      contrast: 0.3
      brightness: 0.3
      saturation: 0.2
    random_rotation: 10
    horizontal_flip: 0.5
    gaussian_blur:
      kernel_size: 7
      sigma: [0.1, 3.0]

eval_config:
  eval_scales: [0.5, 1, 2]
  horrizontal_flip: no
  output_stride: 16 # NOT IMPEMENTED

inference_config:
  precision: medium
  output_stride: 16 # NOT IMPEMENTED

logs_dir: /mnt/logs