model_config:
  name: Adam-lr_1e-3
  architecture: deeplabv3
  backbone: mobilenet_v3_large
  num_classes: 20
  unfreeze_at: block6a_expand_activation
  output_stride: 16
  activation: leaky_relu
  dropout_rate: 0

dataset_config:
  name: Cityscapes
  path: /mnt/dataset/Cityscapes/
  version: fine
  num_train_batches: 1.0 # 1.0 means 100% 
  num_eval_batches: 1.0
  batch_size: 6
  shuffle: yes
  num_workers: 3

train_config:
  loss: CrossEntropyLoss
  epochs: 80
  precision: high
  distribute:
    strategy: ddp
    devices: 2
    sync_batchnorm: yes
  optimizer:
    name: Adam
    #weight_decay: 0.00001
    learning_rate: 1e-3
  lr_schedule:
    warmup_method: linear
    warmup_epochs: 50
    warmup_decay: 0.01
    main_schedule: polynomial
    main_schedule_epochs: 20
    power: 2

  # augmentations: 
  #   color_jitter: 
  #     contrast: 0.3
  #     brightness: 0.3
  #     saturation: 0.2
  #   horizontal_flip:
  #   gaussian_blur:
  #     sigma: [0.1, 3.0]

eval_config:
  eval_scales: [0.5, 1, 2]
  horrizontal_flip: no

inference_config:
  precision: high

logs_dir: /mnt/logs
