name: Hadolint

on:
  push:
    branches: [ master, main ]
    paths: 
      - '**Dockerfile'
      - '.github/workflows/hadolint.yaml'
  pull_request:
    branches: [ master, main ]
    paths: 
      - '**Dockerfile'
      - '.github/workflows/hadolint.yaml'

permissions:
  contents: read # for actions/checkout to fetch code
  security-events: write # for github/codeql-action/upload-sarif to upload SARIF results
  actions: read # only required for a private repository by github/codeql-action/upload-sarif to get the Action run status

jobs:  
  hadolint:    
    strategy:
      fail-fast: false
      matrix:
        dockerfile:
          # List of all Dockerfiles to be linted
          - .devcontainer/pytorch.Dockerfile
    
    uses: KostasStefanidis/github-workflows/.github/workflows/hadolint.yaml@main
    with:
      dockerfile: ${{ matrix.dockerfile }}
