name: Hadolint

on:
  push:
    branches: [ master, main ]
    paths: 
      - '**Dockerfile'
      - '.github/workflows/hadolint.yaml'
  pull_request:
    branches: [ master, main ]
    paths: 
      - '**Dockerfile'
      - '.github/workflows/hadolint.yaml'

permissions:
  contents: read # for actions/checkout to fetch code
  security-events: write # for github/codeql-action/upload-sarif to upload SARIF results
  actions: read # only required for a private repository by github/codeql-action/upload-sarif to get the Action run status

jobs:
  discover-dockerfiles:
    name: Discover Dockerfiles in repository
    runs-on: ubuntu-latest
    outputs:
      dockerfiles: ${{ steps.discover.outputs.dockerfiles }}
    steps:
      - name: Checkout code
        id: checkout
        uses: actions/checkout@v4

      - name: Discover Dockerfiles
        id: discover
        run: |
          echo "dockerfiles=$(git ls-files | grep 'Dockerfile$' | sed 's/.*/"&"/' | paste -sd, -)" >> $GITHUB_OUTPUT
  
  hadolint:
    needs: discover-dockerfiles
    
    strategy:
      fail-fast: false
      matrix:
        dockerfile: ${{ needs.discover-dockerfiles.outputs.dockerfiles }}
    
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        run: |
          echo ${{ matrix.dockerfile }}
    # uses: KostasStefanidis/github-workflows/.github/workflows/hadolint.yaml@main
    # with:
    #   dockerfile: ${{ matrix.dockerfile }}
