name: Pylint

on:
  push:
    branches: [ master, main ]
    paths:
      - '**.py'
      - '.github/workflows/pylint.yaml'
      - 'requirements.txt'
  pull_request:
    branches: [ master, main ]
    paths:
      - '**.py'
      - '.github/workflows/pylint.yaml'
      - 'requirements.txt'
  workflow_dispatch:

jobs:
  pylint:
    permissions:
      # required for all workflows
      security-events: write
      # only required for workflows in private repositories
      actions: read
      contents: read
    
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10"]
    
    uses: KostasStefanidis/github-workflows/.github/workflows/pylint.yaml@main
    with:
      python_version: ${{ matrix.python-version }}
