name: Pyre

on:
  push:
    branches: [ master, main ]
    paths: 
      - '**.py'
      - '.github/workflows/pyre.yaml'
  pull_request:
    branches: [ master, main ]
    paths: 
      - '**.py'
      - '.github/workflows/pyre.yaml'

permissions:
  contents: read # for actions/checkout to fetch code
  security-events: write # for github/codeql-action/upload-sarif to upload SARIF results
  actions: read # only required for a private repository by github/codeql-action/upload-sarif to get the Action run status

jobs:
  pyre:
    uses: KostasStefanidis/github-workflows/.github/workflows/pyre.yaml@main
