name: Pyre

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  pyre:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Run Pyre Action
        uses: facebook/pyre-action@v0.0.1
        with:
            repo-directory: './'
            requirements-path: '.devcontainer/requirements.txt'
