name: Pyre

on:
  push:
    branches: [ main ]
    paths: 
      - '**.py'
      - '.github/workflows/pyre.yaml'
  pull_request:
    branches: [ main ]
    paths: 
      - '**.py'
      - '.github/workflows/pyre.yaml'

permissions:
  contents: read

jobs:
  pyre:
    runs-on: ubuntu-latest

    permissions:
      contents: read # for actions/checkout to fetch code
      security-events: write # for github/codeql-action/upload-sarif to upload SARIF results
      actions: read # only required for a private repository by github/codeql-action/upload-sarif to get the Action run status
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Pyre Action
        uses: facebook/pyre-action@v0.0.1
        with:
          repo-directory: './'
          requirements-path: '.devcontainer/requirements.txt'
