name: Pysa

on:
  push:
    branches: [ master, main ]
    paths: 
      - '**.py'
      - '.github/workflows/pysa.yaml'
  pull_request:
    branches: [ master, main ]
    paths: 
      - '**.py'
      - '.github/workflows/pysa.yaml'

permissions:
  actions: read
  contents: read
  security-events: write

jobs:
  pysa:
    uses: KostasStefanidis/github-workflows/.github/workflows/pysa.yaml@main
